# Generated by Django 3.2.5 on 2021-07-04 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csa', '0002_remove_companies_companyid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='Filename',
            field=models.FileField(blank=True, max_length=300, null=True, upload_to=None),
        ),
    ]
