# Generated by Django 3.2.5 on 2021-07-12 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csa', '0003_alter_companies_filename'),
    ]

    operations = [
        migrations.CreateModel(
            name='caiq_company_map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CAIQResponseVersions', models.CharField(max_length=300)),
                ('CompanyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csa.companies')),
            ],
        ),
    ]
